services:
  api:
    build:
      context: ../
      platforms:
        - linux/amd64
        - linux/arm64
    env_file:
      - .env
    ports:
      - 8080:8080

  mongodb:
    image: mongo:8.0
    restart: unless-stopped
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
